name: 'Needs triage'
description: 'Add "Needs triage" label to a new issue'
author: 'capdiem'
branding:
  icon: 'tag'
  color: 'purple'
inputs:
  repoToken:
    description: 'Github token for the repository'
    required: true
  eventType:
    description: 'the activity type of current event, should be github.event.action"'
    required: true
  labelName:
    description: 'The label name'
    default: 'Needs triage'
  secondsUtilLabel:
    description: 'The number of seconds before the issue is automatically marked "Needs triage"'
    default: '60'
  goodFirstIssue:
    description: 'Add "good first issue" for newcomeres'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
